#!/usr/bin/env ruby

mydir = File.dirname(File.expand_path($0))
skip = [".", "..", ".git",".gitmodules", "init", "README"]
myhome = ENV['HOME']

for entry in Dir.entries(mydir)
  next if skip.member? entry
  src = File.join(mydir, entry)
  dst = File.join(myhome, entry.insert(0,"."))
  if File.symlink? dst or not File.exists? dst then
    File.unlink dst if File.exists? dst
    File.symlink(src, dst)
    puts "#{src} -> #{dst}"
  else
    puts "Refusing to touch #{dst}, not a symlink"
  end
end

# vim: set ft=ruby et ts=2 sw=2 tw=79: 
