[options]
  colorscheme = "onedark"
  colorscheme_bg = "dark"
  enable_guicolors = true
  statusline_separator = "nil"
  statusline_inactive_separator = "bar"
  buffer_index_type = 4
  enable_tabline_filetype_icon = false
  enable_statusline_mode = true

[[custom_plugins]]
  repo = "https://github.com/hashivim/vim-terraform.git"

[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "denite"

[[layers]]
  name = "tmux"

[[layers]]
  name = "cscope"

[[layers]]
  name = "debug"

[[layers]]
  name = "edit"

[[layers]]
  name = "git"

[[layers]]
  name = "tags"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#extra" 

[[layers]]
  name = "lang#erlang"

[[layers]]
  name = "lang#elm"

[[layers]]
  name = "lang#elixir"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#clojure"

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#scala"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#ruby"
  repl_command = "pry"

[[layers]]
  name = "lang#r"

[[layers]]
  name = "lang#python"
  format-on-save = 1

[[layers]]
  name = "lang#php"

[[layers]]
  name = "lang#perl"

[[layers]]
  name = "lang#ocaml"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#lua"

[[layers]]
  name = "lang#lisp"

[[layers]]
  name = "lang#latex"

[[layers]]
  name = "lang#kotlin"

[[layers]]
  name = "lang#javascript"
  auto_fix = true
  enable_flow_syntax = true

[[layers]]
  name = "lang#java"

[[layers]]
  name = "lang#ipynb"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#haskell"

[[layers]]
  name = "lang#graphql"

[[layers]]
  name = "lang#jinja"

[[layers]]
  name = "colorscheme"
